---

- name: Add Artifactory Pro RPM
  yum_repository:
    name: artifactory-pro-rpms
    description: Artifactory Pro
    baseurl: https://jfrog.bintray.com/artifactory-pro-rpms
  when: artifactory_type | lower == 'pro'

- name: Add Artifactory OSS RPM
  yum_repository:
    name: artifactory-rpms
    description: Artifactory OSS
    baseurl: https://jfrog.bintray.com/artifactory-rpms
  when: artifactory_type | lower == 'oss'

- name: Add Jfrog Container Registry RPM
  yum_repository:
    name: container-registry-rpms
    description: JFrog Container Registry
    baseurl: https://bintray.com/jfrog/artifactory-rpms/jfrog-artifactory-jcr-rpm
  when: artifactory_type | lower == 'jcr'

  
- name: Install Artifactory
  yum:
    name: "jfrog-artifactory-{{ artifactory_type | lower }}"
    state: present
  notify:
    - restart artifactory
    - restart apache
